# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc = '0.8.23'
vm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 200
block_number = 14126430
block_timestamp = 1643802347
runs = 4096
libs = ["node_modules", "lib"]

[profile.fork] # run via FOUNDRY_PROFILE=fork foundry test

[profile.ci_sizes]
optimizer_runs = 200

[invariant] 
fail_on_revert = false

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
